site_name: Memories
repo_url: https://github.com/pulsejet/memories
repo_name: pulsejet/memories
copyright: Copyright &copy; 2022 - 2023 Varun Patil

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7Dr9f9vNjJ
    - icon: fontawesome/brands/github
      link: https://github.com/pulsejet/memories

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/camera
  custom_dir: docs/overrides

plugins:
  - search
  - social

nav:
  - Home: 'index.md'
  - Getting started:
      - 'install.md'
      - 'config.md'
      - 'file-types.md'
      - 'hw-transcoding.md'
      - 'troubleshooting.md'
      - 'system-config.md'
  - Support:
      - 'faq.md'
      - 'changelog.md'
      - 'memories-vs-photos.md'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
