site_name: Memories
repo_url: https://github.com/pulsejet/memories
repo_name: pulsejet/memories
demo_url: https://memories-demo.radialapps.com/apps/memories/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
  palette:
    primary: blue
  icon:
    logo: material/camera
  custom_dir: docs/overrides

nav:
  - Home: 'index.md'
  - Getting started:
      - 'config.md'
      - 'file-types.md'
      - 'hw-transcoding.md'
      - 'system-config.md'
  - Support:
      - 'changelog.md'
      - 'faq.md'
      - 'memories-vs-photos.md'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
