name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        make dev-setup
        make build-js-production
        ./bundle.sh

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "memories.tar.gz"